### ISSUE TITLE
No webserver to run the app : Introducing webpack-dev-server

### ISSUE THREAD

**Issue by ipernet** [btholt/complete-intro-to-react#26]
Hi @btholt 

There is nowhere in the tutorial an explanation on how to run the app. 

So by default I suppose that most people will open `index.html` in the browser (file system), which works till external resources must be loaded (when starting to load the shows pics in the "browse all" pages which use absolute URLs, which does not work).

My suggestion is to introduce  **webpack-dev-server** just before the _React Router_ section, so once people got familiar with running webpack and start using its "watch" ability.

The addition only asked for a minimal replacement of "webpack" with "webpack-dev-server" in  `package.json` and offers at that moment 1) a UI to the "watch" ability just introduced 2) A basic express server to serve the app, needed for the next section to correctly load shows pics.

No code must be changed, hence the relevancy of introducing/using it to me at that moment.

If you're ok with that I'll send a PR!

**Comment by btholt** [comment]
This is a great idea. I really should have considered it in the first place. However the issue is this course corresponds to videos on Frontend Masters and I'd need to update the videos to use it.

However, we're in luck. As it happens, I'm in the process of updating the course and to update the videos in December. So I will go ahead and incorporate this in when I do that. So I appreciate the offer of the PR but I'll work in myself as I update the class.

Thanks!
